name: 🚀 Feature Request
description: Please provide a detailed description of the feature you are requesting.
title: "[Request]: "
labels: ["enhancement"]
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: I confirm that this new request is necessary.
      required: true
- type: textarea
  attributes:
    label: Describe your feature request
    description: Please provide a detailed description of the feature you are requesting.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context about the feature here.
  validations:
    required: false
